title: Site title
author: Site Autor

# use gh-pages to create live demo at matiasdahl.github.io/homepage-theme/
baseurl: "/homepage-theme"

date_format: "%Y-%m-%d"

google_analytics:
disqus_shortname:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'no_intra_emphasis']

permalink:    /blog/:year/:title
